openapi: 3.0.3
info:
  title: fundock - API 1.0
  description: |-
    The `fundock` API lets you manage and run functions over an HTTP API.
    
    Some useful links:
    - [Live version of this API doc](https://github.com/sparkymat/fundock/blog/main/swagger.yaml)
  license:
    name: AGPL v3
    url: https://www.gnu.org/licenses/agpl-3.0.en.html
  version: 1.0.0
tags:
  - name: functions
    description: Everything about functions
  - name: invocations
    description: Record of function executions or invocations
paths:
  /api/functions:
    post:
      tags:
        - functions
      summary: Add a new function
      description: Add a new function
      operationId: functionCreate
      requestBody:
        description: Create a new function
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/functionCreateInput'
        required: true
      responses:
        '200':
          description: Successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/function'
        '422':
          description: Invalid input
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/invalidInputError'
        '500':
          description: Internal server error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/internalServerError'
      security:
        - api_key: []
    get:
      tags:
        - functions
      summary: Get list of functions
      description: Gets a paginated list of functions
      operationId: functionsList
      parameters:
        - name: page_size
          in: query
          schema:
            type: integer
          required: true
          description: Size of the page to fetch
        - name: page_number
          in: query
          schema:
            type: integer
          required: true
          description: Page number to fetch
      responses:
        '200':
          description: Successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/functionsList'
        '500':
          description: Internal server error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/internalServerError'
      security:
        - api_key: []
  /api/fn/{name}:
    get:
      tags:
        - functions
      summary: Fetch function details
      description: Get details of the specified function
      operationId: functionShow
      parameters:
        - name: name
          in: path
          schema:
            type: string
          required: true
          description: name of the function
      responses:
        '200':
          description: Successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/function'
        '500':
          description: Internal server error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/internalServerError'
      security:
        - api_key: []
  /api/fn/{name}/exec:
    post:
      tags:
        - functions
      summary: Execute a function synchronously
      description: Execute a function synchronously and get the output
      operationId: functionExec
      parameters:
        - name: name
          in: path
          schema:
            type: string
          required: true
          description: name of the function
      responses:
        '200':
          description: Successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/invocation'
        '500':
          description: Internal server error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/internalServerError'
      security:
        - api_key: []
  /api/fn/{name}/start:
    post:
      tags:
        - functions
      summary: Execute a function asynchronously
      description: Execute a function asynchronously
      operationId: functionStart
      parameters:
        - name: name
          in: path
          schema:
            type: string
          required: true
          description: name of the function
      responses:
        '200':
          description: Successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/invocation'
        '500':
          description: Internal server error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/internalServerError'
      security:
        - api_key: []
  /api/invocations:
    get:
      tags:
        - invocations
      summary: Get list of invocations
      description: Gets a paginated list of invocations
      operationId: invocationsList
      parameters:
        - name: page_size
          in: query
          schema:
            type: integer
          required: true
          description: Size of the page to fetch
        - name: page_number
          in: query
          schema:
            type: integer
          required: true
          description: Page number to fetch
        - name: fn
          in: query
          schema: 
            type: string
          required: false
          description: Name of function to filter by
      responses:
        '200':
          description: Successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/invocationsList'
        '500':
          description: Internal server error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/internalServerError'
      security:
        - api_key: []
  /api/invocations/{id}:
    get:
      tags:
        - invocations
      summary: Get details of an invocation
      description: Gets details of an invocation
      operationId: invocationShow
      parameters:
        - name: id
          in: path
          schema:
            type: string
            format: uuid
          required: true
          description: ID of the invocation to fetch
      responses:
        '200':
          description: Successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/invocation'
        '500':
          description: Internal server error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/internalServerError'
      security:
        - api_key: []
components:
  schemas:
    invocationsList:
      type: object
      properties:
        page_size:
          type: integer
          example: 20
        page_number:
          type: integer
          example: 1
        items:
          type: array
          items:
            $ref: '#/components/schemas/invocation'
    invocation:
      type: object
      properties:
        id:
          type: string
          format: uuid
          example: a-b-c-d
        started_time:
          type: string
          format: date-time
        ended_time:
          type: string
          format: date-time
        output:
          type: string
    functionsList:
      type: object
      properties:
        page_size:
          type: integer
          example: 20
        page_number:
          type: integer
          example: 1
        items:
          type: array
          items:
            $ref: '#/components/schemas/function'
    function:
      type: object
      properties:
        id:
          type: string
          format: uuid
          example: a-b-c-d
        name:
          type: string
          example: hello
        image:
          type: string
          example: docker.io/hello-world:latest
        skip_logging:
          type: boolean
          example: false
        created_time:
          type: string
          format: date-time
    functionCreateInput:
      required:
        - name
        - image
        - skip_logging
      type: object
      properties:
        name:
          type: string
          example: hello
        image:
          type: string
          example: docker.io/hello-world:latest
        skip_logging:
          type: boolean
          example: false
    invalidInputError:
      type: object
      properties:
        error:
          type: string
          example: invalid input
    internalServerError:
      type: object
      properties:
        error:
          type: string
          example: internal server error
  securitySchemes:
    api_key:
      type: apiKey
      name: X-Api-Key
      in: header