openapi: 3.0.3
info:
  title: fundock - API 1.0
  description: |-
    The `fundock` API lets you manage and run functions over an HTTP API.
    
    Some useful links:
    - [Live version of this API doc](https://github.com/sparkymat/fundock/blog/main/swagger.yaml)
  license:
    name: AGPL v3
    url: https://www.gnu.org/licenses/agpl-3.0.en.html
  version: 1.0.0
tags:
  - name: functions
    description: Everything about functions
  - name: invocations
    description: Record of function executions or invocations
  - name: users
    description: Operations about users
paths:
  /api/functions:
    post:
      tags:
        - functions
      summary: Add a new function
      description: Add a new function
      operationId: addFunction
      requestBody:
        description: Create a new function
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/functionCreateInput'
        required: true
      responses:
        '200':
          description: Successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/function'
        '422':
          description: Invalid input
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/invalidInputError'
        '500':
          description: Internal server error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/internalServerError'
      security:
        - api_key: []
components:
  schemas:
    function:
      type: object
      properties:
        id:
          type: string
          format: uuid
          example: a-b-c-d
        name:
          type: string
          example: hello
        image:
          type: string
          example: docker.io/hello-world:latest
        skip_logging:
          type: boolean
          example: false
        created_time:
          type: string
          format: date-time
    functionCreateInput:
      required:
        - name
        - image
        - skip_logging
      type: object
      properties:
        name:
          type: string
          example: hello
        image:
          type: string
          example: docker.io/hello-world:latest
        skip_logging:
          type: boolean
          example: false
    invalidInputError:
      type: object
      properties:
        error:
          type: string
          example: invalid input
    internalServerError:
      type: object
      properties:
        error:
          type: string
          example: internal server error
  securitySchemes:
    api_key:
      type: apiKey
      name: X-Api-Key
      in: header
