name: CI

on:
  push:
    branches:
      - '**'

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v3
        with:
          go-version: '^1.19'
      - name: golangci-lint
        uses: golangci/golangci-lint-action@v3
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v3
        with:
          go-version: '^1.19'
      - name: go test
        run: |
          go test ./...
  api-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Run API tests
        run: |
          docker-compose -f docker-compose.ci.yml up -d
          sleep 3
          PGPASSWORD=fundock psql -h localhost -U postgres -w fundock < api-test/seed.sql
          curl -H 'X-Api-Key: foobar' "http://localhost:8080/api/functions?page_size=20&page_number=1"
  checks-passed:
    runs-on: ubuntu-latest
    needs:
      [
        lint,
        test
      ]
    steps:
      - name: done
        run: |
          echo Done
