name: CI

on:
  push:
    branches:
      - '**'

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v3
        with:
          go-version: '^1.19'
      - name: golangci-lint
        uses: golangci/golangci-lint-action@v3
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v3
        with:
          go-version: '^1.19'
      - name: go test
        run: |
          go test ./...
  checks-passed:
    runs-on: ubuntu-latest
    needs:
      [
        lint,
        test
      ]
    steps:
      - name: done
        run: |
          echo Done
