// Code generated by qtc from "error.qtpl". DO NOT EDIT.
// See https://github.com/valyala/quicktemplate for details.

//line view/error.qtpl:1
package view

//line view/error.qtpl:1
import (
	qtio422016 "io"

	qt422016 "github.com/valyala/quicktemplate"
)

//line view/error.qtpl:1
var (
	_ = qtio422016.Copy
	_ = qt422016.AcquireByteBuffer
)

//line view/error.qtpl:1
func StreamError(qw422016 *qt422016.Writer, message string) {
//line view/error.qtpl:1
	qw422016.N().S(`
  <div class="uk-flex uk-flex-center">
    <div class="uk-card uk-card-hover uk-card-secondary uk-card-body uk-width-1-1 uk-width-1-3@m uk-margin-large-top">
      <h3 class="uk-card-title">Error</h3>
      <p>`)
//line view/error.qtpl:5
	qw422016.E().S(message)
//line view/error.qtpl:5
	qw422016.N().S(`</p>
    </div>
  </div>
`)
//line view/error.qtpl:8
}

//line view/error.qtpl:8
func WriteError(qq422016 qtio422016.Writer, message string) {
//line view/error.qtpl:8
	qw422016 := qt422016.AcquireWriter(qq422016)
//line view/error.qtpl:8
	StreamError(qw422016, message)
//line view/error.qtpl:8
	qt422016.ReleaseWriter(qw422016)
//line view/error.qtpl:8
}

//line view/error.qtpl:8
func Error(message string) string {
//line view/error.qtpl:8
	qb422016 := qt422016.AcquireByteBuffer()
//line view/error.qtpl:8
	WriteError(qb422016, message)
//line view/error.qtpl:8
	qs422016 := string(qb422016.B)
//line view/error.qtpl:8
	qt422016.ReleaseByteBuffer(qb422016)
//line view/error.qtpl:8
	return qs422016
//line view/error.qtpl:8
}
