// Code generated by qtc from "function_show.qtpl". DO NOT EDIT.
// See https://github.com/valyala/quicktemplate for details.

//line view/function_show.qtpl:1
package view

//line view/function_show.qtpl:1
import "github.com/sparkymat/fundock/presenter"

//line view/function_show.qtpl:3
import (
	qtio422016 "io"

	qt422016 "github.com/valyala/quicktemplate"
)

//line view/function_show.qtpl:3
var (
	_ = qtio422016.Copy
	_ = qt422016.AcquireByteBuffer
)

//line view/function_show.qtpl:3
func StreamFunctionShow(qw422016 *qt422016.Writer, fn presenter.Function) {
//line view/function_show.qtpl:3
	qw422016.N().S(`
  <div class="uk-padding uk-flex uk-flex-column">
    <h1>`)
//line view/function_show.qtpl:5
	qw422016.E().S(fn.Name)
//line view/function_show.qtpl:5
	qw422016.N().S(`</h1>
    <p class="uk-margin-small">
      <span uk-icon="info"></span>
      `)
//line view/function_show.qtpl:8
	qw422016.E().S(fn.Image)
//line view/function_show.qtpl:8
	qw422016.N().S(`
    </p>
    `)
//line view/function_show.qtpl:10
	if fn.SkipLogging {
//line view/function_show.qtpl:10
		qw422016.N().S(`
      <p>Input and output is not logged</p>
    `)
//line view/function_show.qtpl:12
	} else {
//line view/function_show.qtpl:12
		qw422016.N().S(`
      <p>Input and output is logged</p>
    `)
//line view/function_show.qtpl:14
	}
//line view/function_show.qtpl:14
	qw422016.N().S(`
    <div>
      <button class="uk-button uk-button-primary">Run</button>
      <button class="uk-button uk-button-danger">Delete</button>
    </div>
    <h3>Invocations</h3>
    <table class="uk-table uk-table-striped">
      <thead>
      </thead>
      <tbody>
      </tbody>
    </table>
  </div>
`)
//line view/function_show.qtpl:27
}

//line view/function_show.qtpl:27
func WriteFunctionShow(qq422016 qtio422016.Writer, fn presenter.Function) {
//line view/function_show.qtpl:27
	qw422016 := qt422016.AcquireWriter(qq422016)
//line view/function_show.qtpl:27
	StreamFunctionShow(qw422016, fn)
//line view/function_show.qtpl:27
	qt422016.ReleaseWriter(qw422016)
//line view/function_show.qtpl:27
}

//line view/function_show.qtpl:27
func FunctionShow(fn presenter.Function) string {
//line view/function_show.qtpl:27
	qb422016 := qt422016.AcquireByteBuffer()
//line view/function_show.qtpl:27
	WriteFunctionShow(qb422016, fn)
//line view/function_show.qtpl:27
	qs422016 := string(qb422016.B)
//line view/function_show.qtpl:27
	qt422016.ReleaseByteBuffer(qb422016)
//line view/function_show.qtpl:27
	return qs422016
//line view/function_show.qtpl:27
}
