// Code generated by qtc from "functions.qtpl". DO NOT EDIT.
// See https://github.com/valyala/quicktemplate for details.

//line view/functions.qtpl:1
package view

//line view/functions.qtpl:1
import "github.com/sparkymat/fundock/presenter"

//line view/functions.qtpl:3
import (
	qtio422016 "io"

	qt422016 "github.com/valyala/quicktemplate"
)

//line view/functions.qtpl:3
var (
	_ = qtio422016.Copy
	_ = qt422016.AcquireByteBuffer
)

//line view/functions.qtpl:3
func StreamFunctions(qw422016 *qt422016.Writer, functions []presenter.Function) {
//line view/functions.qtpl:3
	qw422016.N().S(`
  <div>
    `)
//line view/functions.qtpl:5
	for _, fn := range functions {
//line view/functions.qtpl:5
		qw422016.N().S(`
      <div>
        <h3>`)
//line view/functions.qtpl:7
		qw422016.E().S(fn.Name)
//line view/functions.qtpl:7
		qw422016.N().S(`</h3>
      </div>
    `)
//line view/functions.qtpl:9
	}
//line view/functions.qtpl:9
	qw422016.N().S(`
  </div>
`)
//line view/functions.qtpl:11
}

//line view/functions.qtpl:11
func WriteFunctions(qq422016 qtio422016.Writer, functions []presenter.Function) {
//line view/functions.qtpl:11
	qw422016 := qt422016.AcquireWriter(qq422016)
//line view/functions.qtpl:11
	StreamFunctions(qw422016, functions)
//line view/functions.qtpl:11
	qt422016.ReleaseWriter(qw422016)
//line view/functions.qtpl:11
}

//line view/functions.qtpl:11
func Functions(functions []presenter.Function) string {
//line view/functions.qtpl:11
	qb422016 := qt422016.AcquireByteBuffer()
//line view/functions.qtpl:11
	WriteFunctions(qb422016, functions)
//line view/functions.qtpl:11
	qs422016 := string(qb422016.B)
//line view/functions.qtpl:11
	qt422016.ReleaseByteBuffer(qb422016)
//line view/functions.qtpl:11
	return qs422016
//line view/functions.qtpl:11
}
