// Code generated by qtc from "new_function.qtpl". DO NOT EDIT.
// See https://github.com/valyala/quicktemplate for details.

//line view/new_function.qtpl:1
package view

//line view/new_function.qtpl:1
import (
	qtio422016 "io"

	qt422016 "github.com/valyala/quicktemplate"
)

//line view/new_function.qtpl:1
var (
	_ = qtio422016.Copy
	_ = qt422016.AcquireByteBuffer
)

//line view/new_function.qtpl:1
func StreamNewFunction(qw422016 *qt422016.Writer, csrfToken string) {
//line view/new_function.qtpl:1
	qw422016.N().S(`
  <div class="uk-padding uk-flex uk-flex-column">
    <h3 class="uk-text-center">Add new function</h3>
    <form action="/functions" method="POST">
      <input type="hidden" name="csrf" value="`)
//line view/new_function.qtpl:5
	qw422016.E().S(csrfToken)
//line view/new_function.qtpl:5
	qw422016.N().S(`">
      <div class="uk-form-controls">
        <input class="uk-input" id="name" type="text" name="name" placeholder="Enter name e.g. hello" required>
      </div>
      <div class="uk-form-controls uk-margin-top">
        <input class="uk-input" id="image" type="text" name="image" placeholder="Enter image. e.g docker.io/hello-world:latest" required>
      </div>
      <div class="uk-margin uk-grid-small uk-child-width-auto uk-grid">
        <label><input class="uk-checkbox" type="checkbox" name="skip_logging"> Skip logging?</label>
      </div>
      <input type="submit" value="Add" class="uk-button uk-button-primary uk-float-right uk-margin-top">
    </form>
  </div>
`)
//line view/new_function.qtpl:18
}

//line view/new_function.qtpl:18
func WriteNewFunction(qq422016 qtio422016.Writer, csrfToken string) {
//line view/new_function.qtpl:18
	qw422016 := qt422016.AcquireWriter(qq422016)
//line view/new_function.qtpl:18
	StreamNewFunction(qw422016, csrfToken)
//line view/new_function.qtpl:18
	qt422016.ReleaseWriter(qw422016)
//line view/new_function.qtpl:18
}

//line view/new_function.qtpl:18
func NewFunction(csrfToken string) string {
//line view/new_function.qtpl:18
	qb422016 := qt422016.AcquireByteBuffer()
//line view/new_function.qtpl:18
	WriteNewFunction(qb422016, csrfToken)
//line view/new_function.qtpl:18
	qs422016 := string(qb422016.B)
//line view/new_function.qtpl:18
	qt422016.ReleaseByteBuffer(qb422016)
//line view/new_function.qtpl:18
	return qs422016
//line view/new_function.qtpl:18
}
